name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: setup
        uses: haskell-actions/setup@v2
        with:
          ghc-version: 9.4
          cabal-update: true
      - id: cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: cabal-${{ hashFiles('**/*.cabal') }}

      - run: cabal install --only-dependencies
        if: steps.cache.outputs.cache-hit != 'true'

      - uses: actions/cache/save@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - run: cabal install
      - run: site build

      - uses: actions/upload-pages-artifact@v2
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
